PREFIX text: <http://jena.apache.org/text#>
PREFIX apf: <http://jena.hpl.hp.com/ARQ/property#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX actors: <http://ldf.fi/warsa/actors/>
PREFIX etype: <http://ldf.fi/warsa/events/event_types/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX cas: <http://ldf.fi/schema/narc-menehtyneet1939-45/>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?id ?ngram ?label ?firstNames ?familyName {
  VALUES ?ngram {
    <VALUES>
  }
  BIND(CONCAT('"',?ngram,'"') AS ?qstring)
  GRAPH <http://ldf.fi/warsa/actors> { ?id text:query ?qstring . }
  ?id foaf:familyName ?familyName .
  FILTER(str(?familyName) = ?ngram)
  ?id skos:prefLabel ?label .
  OPTIONAL { ?id foaf:firstName ?firstNames . }
}
