PREFIX text: <http://jena.apache.org/text#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?id ?ngram ?label ?firstNames ?familyName {
  VALUES ?ngram {
    <VALUES>
  }
  BIND(CONCAT('"',?ngram,'"') AS ?qstring)
  GRAPH <http://ldf.fi/warsa/actors> { ?id text:query ?qstring . }
  ?id foaf:familyName ?familyName .
  FILTER(str(?familyName) = ?ngram)
  ?id skos:prefLabel ?label .
  OPTIONAL { ?id foaf:firstName ?firstNames . }
}
